import { TtextObject } from "src/types";

const textObj: TtextObject = {
  items: "items:",
  titleProd: "Products In Cart",
  page: "page:",
  separLeft: "<",
  count: "1",
  separRight: ">",
  prodName: "iPhone 9",
  desc: "An apple mobile which is nothing like apple",
  rating: "Rating",
  ratNum: "4.69",
  disc: "Discount",
  itemNumb: "1",
  discNum: "12.96%",
  stock: "Stock:",
  stockNum: "94",
  incr: "+",
  decr: "-",
  summaryTitle: "Summary",
  buyBtn: "buy now",
  products: "Products:",
  itemQt: "1",
  prodAmt: "1",
  total: "Total",
  testPromo: "Promo for test: 'RS', 'EPM",
  title1: "Personal details",
  title2: "Credit card details",
  nameErr: "Enter at least two words with a length of at least three chars",
  phoneErr: "Number has to start with '+' and consist of at least 9 numbers",
  addrErr: "Enter at least three words with a length of at least five chars",
  emailErr: "Enter e-mail",
  valid: "Valid:",
  CVV: "CVV:",
  cardNumbErr: "Card number validation: Error: enter 16 numbers",
  validErr: "Card valid thru validation: Error",
  price: "&#8364 549",
  CVVErr: "CVV validation: Error: enter 3 numbers",
  confirmBtn: "confirm",
  totSum: "&#8364 549",
};

export default textObj;
